### ISSUE TITLE
Create a Repository of Scenarios

### ISSUE THREAD

**Issue by andrewbwm** [mal-lang/mal-simulator#21]
Have a repository of scenarios that can be run in the simulator.

- [x] Created a github repository for it at https://github.com/mal-lang/malsim-scenarios
- [x] #31
  - [x] Create trainingLang
  - [x] Create models
  - [x] Add simplified rewards file
  - [ ] Create scripts for simpler training deployment
- [ ] Update repository with improved scenario and environment configuration files (This should be done when #26 and #32 are finished)
- [ ] Add a variety of scenarios and environments

We may wish to copy some of these issues over to the malsim-scenarios repository.

**Comment by mrkickling** [comment]
> Create scripts for simpler training deployment

The CLI can probably be used for it #38

**Comment by mrkickling** [comment]
I have added models to the malsim-scenarios. I tried to start converting the old 'scenarios' (models) to the new, but I did not even get them to load in the first place.
