### ISSUE TITLE
Implement is_observable Property for Observation

### ISSUE THREAD

**Issue by andrewbwm** [mal-lang/mal-simulator#24]
Properly flag which attack steps in the attack graph are observable and include it in the observations sent to agents.

**Comment by andrewbwm** [comment]
Are there situations where maybe we would like to just prune away the unobservable nodes?

**Comment by mrkickling** [comment]
The option to specify observable nodes in scenarios was added in #64 and are applied to the observation in the simulator. Maybe this solves this issue?

**Comment by andrewbwm** [comment]
Implemented in #64
