### ISSUE TITLE
Establish an Environment Description Format

### ISSUE THREAD

**Issue by andrewbwm** [mal-lang/mal-simulator#32]
We should create a environment description format that includes the following information:
- [x] Network Connectivity
- [x] Modelling Assumptions(which assets to create an when based on missing/limited information from the data sources)

For the network connectivity we probably want to come up with some sort of structure where connectivity can be defined between individual systems and/or networks to keep the configuration smaller and more legible.

**Comment by mrkickling** [comment]
This has been worked on in the TYR Monitor (on internal KTH github).
The network connectivity parts are ready to be reviewed, but the assumptions are very 'simple' at the moment.
