### ISSUE TITLE
Make the Attacker Eviction When a Defense is Enabled Configurable

### ISSUE THREAD

**Issue by andrewbwm** [mal-lang/mal-simulator#47]
The behaviour where the attacker is evicted from attack steps if enabling a defense has made them non-traversable should be configurable and disabled by default.

**Comment by andrewbwm** [comment]
This should also make the simulator configurable when it comes to if the actions are permanent/sticky or not.

**Comment by mrkickling** [comment]
This was implemented in #57 so I will close this issue
