### ISSUE TITLE
Implement is_actionable in observation

### ISSUE THREAD

**Issue by mrkickling** [mal-lang/mal-simulator#74]
`is_actionable` will work like `is_observable`, but for steps that are able to lead to actions (being chosen).

In the TYR project for example:
- A defense step will be actionable if we have an action for it in wazuh/tyr monitor, in the same way an attack step is observable if we have an alert for it in wazuh/tyr monitor. 

The idea is that this can be used to optimize training (when the agent only picks a defense that actually has an action related to it).

What needs to be done:

- [x] Update the scenario file to include is_actionable
- [x] Apply `actionable` to attack graph nodes .extras field
- [x] Use in observation to create a vector similar to `is_observable`

**Comment by kasanari** [comment]
I think adding this information to the action mask would be fine.
